/*
 * ConsultaPessoa.java
 *
 * Created on 28 de Outubro de 2009, 19:27
 */

package Telas;

import Bean.Filme;
import Factory.FactoryDAO;
import Dao.FilmeDAO;
import Factory.IFilmeDAO;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Danilo
 */
public class ConsultaFilme extends javax.swing.JDialog {
    
    private static final int COLUNA_ID  = 0;
    private static final int COLUNA_TITULO  = 1;
    private static final int COLUNA_VALOR  = 2;
    
    /** Creates new form ConsultaFilme */
    public ConsultaFilme(java.awt.Frame parent, boolean modal) throws FileNotFoundException, IOException, SQLException, ClassNotFoundException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        atualizaQuantidadeDeLinhas();
        incluiInformacoesNoGrid();
    }
    
    
    private void incluiInformacoesNoGrid() throws FileNotFoundException, IOException, SQLException, ClassNotFoundException{
        DefaultTableModel dtm = (DefaultTableModel)tbFilmes.getModel();

        Filme c = new Filme();
        IFilmeDAO cd = FactoryDAO.getFilmeDAO();

        List<Filme> list = cd.load();

        dtm.setRowCount(0);
        for(int i = 0; i < list.size(); i++){
            acrescentaLinha();
            Filme bean = list.get(i);
            tbFilmes.setValueAt(bean.getId(), i, COLUNA_ID);
            tbFilmes.setValueAt(bean.getTitulo(), i, COLUNA_TITULO);
            tbFilmes.setValueAt(bean.getValor(), i, COLUNA_VALOR);
          }
    }  
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFilmes = new javax.swing.JTable();
        btMaisUmaLinha = new javax.swing.JButton();
        btMenosUmaLinha = new javax.swing.JButton();
        lbLinhas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Filmes");

        btFechar.setText("FECHAR");
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btFecharMousePressed(evt);
            }
        });

        tbFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Título", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tbFilmes);

        btMaisUmaLinha.setText("+");
        btMaisUmaLinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMaisUmaLinhaMousePressed(evt);
            }
        });

        btMenosUmaLinha.setText("-");
        btMenosUmaLinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMenosUmaLinhaMousePressed(evt);
            }
        });

        lbLinhas.setText("Linhas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMaisUmaLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMenosUmaLinha)
                        .addGap(36, 36, 36)
                        .addComponent(lbLinhas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar)
                    .addComponent(btMaisUmaLinha)
                    .addComponent(btMenosUmaLinha)
                    .addComponent(lbLinhas))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMousePressed
        this.dispose();
    }//GEN-LAST:event_btFecharMousePressed

    private void acrescentaLinha(){
        DefaultTableModel dtm = (DefaultTableModel)tbFilmes.getModel();
        int linhas = dtm.getRowCount();
        dtm.setRowCount(linhas+1);
        atualizaQuantidadeDeLinhas();
        
    }
    
    private void btMaisUmaLinhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMaisUmaLinhaMousePressed
        
        acrescentaLinha();
        
    }//GEN-LAST:event_btMaisUmaLinhaMousePressed

    private void atualizaQuantidadeDeLinhas(){
        DefaultTableModel dtm = (DefaultTableModel)tbFilmes.getModel();
        int linhas = dtm.getRowCount();
        this.lbLinhas.setText("Linhas: "+linhas);
    }
    
    private void btMenosUmaLinhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMenosUmaLinhaMousePressed
        DefaultTableModel dtm = (DefaultTableModel)tbFilmes.getModel();
        int linhas = dtm.getRowCount();
        if(linhas > 0){
            dtm.setRowCount(linhas-1);
        }
        atualizaQuantidadeDeLinhas();
        
    }//GEN-LAST:event_btMenosUmaLinhaMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaFilme dialog = null;
                try {
                    dialog = new ConsultaFilme(new javax.swing.JFrame(), true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ConsultaFilme.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ConsultaFilme.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ConsultaFilme.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ConsultaFilme.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btMaisUmaLinha;
    private javax.swing.JButton btMenosUmaLinha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLinhas;
    private javax.swing.JTable tbFilmes;
    // End of variables declaration//GEN-END:variables
    
}
