/*
 * ConsultaCliente.java
 *
 * Created on 28 de Outubro de 2009, 19:27
 */

package Telas;

import Bean.Cliente;
import Factory.FactoryDAO;
import Dao.ClienteDAO;
import Factory.IClienteDAO;
import java.awt.Frame;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Danilo
 */
public class ConsultaCliente extends javax.swing.JDialog {
    
    private static final int COLUNA_CODIGO  = 0;
    private static final int COLUNA_NOME  = 1;
    private static final int COLUNA_EMAIL  = 2;
    private static final int COLUNA_TELEFONE  = 3;
    
    /** Creates new form ConsultaCliente */
    public ConsultaCliente(java.awt.Frame parent, boolean modal) throws FileNotFoundException, IOException, SQLException, ClassNotFoundException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        atualizaQuantidadeDeLinhas();
        incluiInformacoesNoGrid();
    }
    
    
    private void incluiInformacoesNoGrid() throws FileNotFoundException, IOException, SQLException, ClassNotFoundException{
        DefaultTableModel dtm = (DefaultTableModel)tbClientes.getModel();

        Cliente c = new Cliente();
        IClienteDAO cd = FactoryDAO.getClienteDAO();

        List<Cliente> list = cd.load();

        dtm.setRowCount(0);
        for(int i = 0; i < list.size(); i++){
            acrescentaLinha();
            Cliente bean = list.get(i);
            tbClientes.setValueAt(bean.getCodigo(), i, COLUNA_CODIGO);
            tbClientes.setValueAt(bean.getNome(), i, COLUNA_NOME);
            tbClientes.setValueAt(bean.getEmail(), i, COLUNA_EMAIL);
            tbClientes.setValueAt(bean.getTelefone(), i, COLUNA_TELEFONE);
        }
    }  
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbLinhas = new javax.swing.JLabel();
        btIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Clientes");

        btFechar.setText("FECHAR");
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btFecharMousePressed(evt);
            }
        });

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        btAlterar.setText("ALTERAR");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAlterarMousePressed(evt);
            }
        });
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("EXCLUIR");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExcluirMousePressed(evt);
            }
        });
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lbLinhas.setText("Linhas:");

        btIncluir.setText("INCLUIR");
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btIncluirMousePressed(evt);
            }
        });
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lbLinhas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLinhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar)
                    .addComponent(btIncluir)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMousePressed
        this.dispose();
    }//GEN-LAST:event_btFecharMousePressed

    private void acrescentaLinha(){
        DefaultTableModel dtm = (DefaultTableModel)tbClientes.getModel();
        int linhas = dtm.getRowCount();
        dtm.setRowCount(linhas+1);
        atualizaQuantidadeDeLinhas();
        
    }
    
    private void btAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMousePressed
        try {
            if (tbClientes.getSelectedRow() == -1) {
                throw new Exception("Selecione ao menos uma linha");
            }

            int linha = tbClientes.getSelectedRow();

            Integer codigo = (Integer) tbClientes.getValueAt(linha, COLUNA_CODIGO);
            String nome = (String) tbClientes.getValueAt(linha, COLUNA_NOME);
            String email = (String) tbClientes.getValueAt(linha, COLUNA_EMAIL);
            String telefone = (String) tbClientes.getValueAt(linha, COLUNA_TELEFONE);


            Cliente cliente = new Cliente();
            cliente.setCodigo(codigo);
            System.out.println("NO BOTAO DE ALTERAR O GET DO CODIGO DE CLIENTE É: "+ cliente.getCodigo());
            cliente.setNome(nome);
            cliente.setEmail(email);
            cliente.setTelefone(telefone);

            Frame pai = (Frame) this.getParent();
            CadastroCliente cad = new CadastroCliente(pai, false, cliente);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       this.dispose();
    }//GEN-LAST:event_btAlterarMousePressed

    private void atualizaQuantidadeDeLinhas(){
        DefaultTableModel dtm = (DefaultTableModel)tbClientes.getModel();
        int linhas = dtm.getRowCount();
        this.lbLinhas.setText("Linhas: "+linhas);
    }
    
    private void btExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMousePressed
        try {
            if (tbClientes.getSelectedRow() == -1) {
                throw new Exception("Selecione ao menos uma linha");
            }

            int linha = tbClientes.getSelectedRow();

            Integer codigo = (Integer) tbClientes.getValueAt(linha, COLUNA_CODIGO);
            String nome = (String) tbClientes.getValueAt(linha, COLUNA_NOME);
            String email = (String) tbClientes.getValueAt(linha, COLUNA_EMAIL);
            String telefone = (String) tbClientes.getValueAt(linha, COLUNA_TELEFONE);

            Cliente cliente = new Cliente();
            cliente.setCodigo(codigo);
            cliente.setNome(nome);
            cliente.setEmail(email);
            cliente.setTelefone(telefone);

            IClienteDAO cd = FactoryDAO.getClienteDAO();
            cd.delete(cliente);
            JOptionPane.showMessageDialog(null, "Cliente '" + cliente.getNome()+ "' foi excluido com sucesso.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        try {
           ConsultaCliente cc = new ConsultaCliente(null, false);
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btExcluirMousePressed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btIncluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMousePressed
        try {
            Frame pai = (Frame) this.getParent();
            CadastroCliente cad = new CadastroCliente(pai, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        this.dispose();
    }//GEN-LAST:event_btIncluirMousePressed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConsultaCliente dialog = null;
                try {
                    dialog = new ConsultaCliente(new javax.swing.JFrame(), true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLinhas;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables
    
}
